### ISSUE TITLE
RTSP  / Async Error in Stream?

### ISSUE THREAD

**Issue by brendan-Tas** [Sunoo/homebridge-camera-ffmpeg#1111]
**Describe The Problem:**

I have been experiencing persistent errors with streams - which have rarely worked but now have stopped altogether - in an RTSP feed via homebridge-camera-ffmpeg. The snapshots do work (wonderfully).
 
In homebridge logs I get an async error straight away on the start of homebridge-camera-ffmpeg.
On stream the error is varied, but at present starts with a Resize command fault (whether or not I specify maxwidth/maxheight or not).

I'm on an rp4b+ with a POE hat.

Any assistance would be very gratefully received as I've tried for months to get a reliable stream that doesn't crash or timeout the system.

Thank you.

**To Reproduce:**

**Logs:**

```
node:17526) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'address' of undefined
    at RTPStreamManagement.generateSetupEndpointResponse (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:998:90)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:959:16
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at StreamingDelegate.prepareStream (/usr/lib/node_modules/homebridge-camera-ffmpeg/src/streamingDelegate.ts:318:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:17526) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17526) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[4/18/2021, 5:50:19 PM] [Camera-ffmpeg] [Front Yard ] Resize command: /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
(node:17526) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'address' of undefined
    at RTPStreamManagement.generateSetupEndpointResponse (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:998:90)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:959:16
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at StreamingDelegate.prepareStream (/usr/lib/node_modules/homebridge-camera-ffmpeg/src/streamingDelegate.ts:318:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:17526) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[4/18/2021, 5:50:35 PM] [Camera-ffmpeg] [Back Yard] Stopped video stream.
```

**Homebridge Config:**

 "cameras": [
                {
                    "name": "Front Yard ",
                    "videoConfig": {
                        "source": "-re -i rtsp://XXX:YYY@192.168.0.201:554/cam/realmonitor?channel=1&subtype=01",
                        "vcodec": "libx264",
                        "encoderOptions": "-ignore_editlist 1 -preset ultrafast",
                        "audio": false,
                        "unbridge": true,
                        "debug": true
                    }
                },
                {
                    "name": "Back Yard",
                    "videoConfig": {
                        "source": "-i rtsp://XXX:YYY8@192.168.0.200:554/cam/realmonitor?channel=1&subtype=00",
                        "vcodec": "libx264",
                        "encoderOptions": "-ignore_editlist 1 -preset ultrafast",
                        "audio": false,
                        "unbridge": true,
                        "debug": true
                    }
                }
            ]

**Environment:**

Raspbian GNU/Linux Buster (10)
HA-Server
192.168.0.100
fe80::1cce:62c6:6e7c:ea48
v12.20.2
v6.14.11
homebridge
/var/lib/homebridge
/var/lib/homebridge/config.json
Yes

**Comment by Sunoo** [comment]
Sorry for the delay, I’ve been moving.

Your symptoms confuse me greatly though. You mention that snapshots work, but that resize step that appears to be failing (according to your logs) only resizes snapshots. If that was what was failing, I’d expect snapshots to fail and live video to work.

Also, the line of code mentioned in the error is calling the callback in prepareStream, and I can’t really think of a way an unhandled exception would occur there.

I’m going to have to give this one some more thought I guess.

**Comment by techbert** [comment]
Same problem here, snapshot requests work but not for the stream, it throws on resize command. I've tried to change a bunch of size related parameters and the urls themselves are confirmed to work using a browser.

```
[5/5/2021, 1:37:33 PM] [Camera-ffmpeg] [Hallen] Resize command: /usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease -f image2 -
TypeError: Cannot read property 'address' of undefined
    at RTPStreamManagement.generateSetupEndpointResponse (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:998:90)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:959:16
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at StreamingDelegate.prepareStream (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/src/streamingDelegate.ts:318:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'address' of undefined
    at RTPStreamManagement.generateSetupEndpointResponse (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:998:90)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:959:16
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at StreamingDelegate.prepareStream (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/src/streamingDelegate.ts:318:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[5/5/2021, 1:37:39 PM] Got SIGTERM, shutting down Homebridge...
```

**Comment by Sunoo** [comment]
Since I just noticed neither of you mentioned it: What version of Homebridge are you running?

**Comment by techbert** [comment]
I'm running `v1.1.2` but now that you mentioned it I might upgrade

**Comment by Sunoo** [comment]
Current versions of this plugin require Homebridge 1.1.3 or newer.

**Comment by techbert** [comment]
Shamefully admitting I completely missed that and that it now works after upgrading to the latest version 🙇

**Comment by Sunoo** [comment]
No worries, glad it was an easy fix.

**Comment by brendan-Tas** [comment]
Apologies, I was, myself away from the computer for a holiday.

@Sunoo - thank you (for this and all your work). I also embarrassingly admit that I had updated the UX but not HA itself and now that I have this issue is resolved!

Thank you again.

**Comment by Sunoo** [comment]
No worries, glad we sorted it out.
