### ISSUE TITLE
Amcrest won't display Live View - Unhandled Promise Rejection?

### ISSUE THREAD

**Issue by 1servo** [Sunoo/homebridge-camera-ffmpeg#1167]
I've recently tried adding my Amcrest IP2M-844E camera and was able to get the device added to HomeKit, where it will display screenshots from the main window. I cannot get the live stream to work however. It gives me a spinning wheel for 3-10 seconds then says that the camera is offline. This is the message I'm getting that talks about a Unhandled Promise Rejection? I'm a bit confused on what is happening.

```
[8/6/2021, 08:22:04] [TplinkSmarthome] Adding: [Flood Light] plug [80068368718CBF70B65CAC68DA4169EF1C27C272]
(node:10497) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'address' of undefined
    at RTPStreamManagement.generateSetupEndpointResponse (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:998:90)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:959:16
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at StreamingDelegate.prepareStream (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/src/streamingDelegate.ts:318:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10497) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10497) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[8/6/2021, 08:22:43] [Camera FFmpeg] [Indoor Camera] Stopped video stream.
```

Below is my configuration for the camera:
```
{
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Indoor Camera",
                    "manufacturer": "Amcrest",
                    "model": "IP2M-844EW",
                    "serialNumber": "XXXXXXXXXXXXXX",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:XXXXX@10.0.0.40:554/cam/realmonitor?channel=1&subtype=0",
                        "stillImageSource": "-i http://admin:XXXXX@10.0.0.40/cgi-bin/snapshot.cgi?chn=1",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15,
                        "maxBitrate": 1024,
                        "encoderOptions": "-async 1 -vsync 1",
                        "vcodec": "copy",
                        "audio": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
```

Running all of this off a Raspberry Pi 3 

OS: Raspbian GNU/Linux Buster (10)
Node.js Version: v12.18.2
Npm Version: v6.14.7

**Comment by Sunoo** [comment]
What version of Homebridge are you running?

**Comment by 1servo** [comment]
Well now I feel stupid. I just looked at my Homebridge and I had a pending update for v1.3.4. That seemed to do the trick!

**Comment by Sunoo** [comment]
Fantastic. Glad you’re working now.
