### ISSUE TITLE
Cant see video fom Aqara G2K and Eufy Security 2k

### ISSUE THREAD

**Issue by Richo005** [Sunoo/homebridge-camera-ffmpeg#1186]
**Describe The Problem:**
 I am really new here so I dont think this is a bug, But I got here while searching for Hoobs support, If this is not the correct channel to get help please let me know whwrw should I go,,,, My problem is that I am not able to see live feed from my cameras in the Hoobs UI

**To Reproduce:**
 I Install the Plugin in Hoobs, I copy and paste The Configuration example that comes in the details section of the plugin, But nothing happened, So i copied one from shared by a User using an Eufy camera 

{
	"platform": "Camera-ffmpeg",
	"cameras": [{
		"name": "Back Yard",
		"videoConfig": {
			"source": "-re -i rtsp://192.168.x.x:554/live0",
			"maxStreams": 2,
			"maxWidth": 1920,
			"maxHeight": 1080,
			"videoFilter": "scale=1280:720"
		}
	}]
}

I change  the IP with the one I got from my reuter, At this moment still nothing apears under Accesories, But in previews tests i saw a black box with the camera name under "Accesories" But If I move the swich in the upper right corner nothing happens, If I enable Streaming and try again I get the messege " The media could not be loaded, either because the server or network failed or because the format is not supported"

**Logs:**

29/8/2021 9:57:05Camera FFmpeg BridgeCamera FFmpeg[Back Yard] Configuring cached bridged accessory...
29/8/2021 9:57:05Camera FFmpeg BridgeBridge is running on port 51826.
29/8/2021 9:57:10Camera FFmpeg BridgeCamera FFmpegERROR[Back Yard] Failed to fetch snapshot.
29/8/2021 9:59:41Camera FFmpeg BridgeCamera FFmpegERROR[Back Yard] Failed to fetch snapshot.
29/8/2021 10:00:51Camera FFmpeg BridgeConfiguration change
29/8/2021 10:00:51cameraffmpegbridge stopping
29/8/2021 10:00:57Camera FFmpeg Bridge starting
29/8/2021 10:01:03Camera FFmpeg BridgeLoaded plugin 'homebridge-camera-ffmpeg'
29/8/2021 10:01:03Camera FFmpeg BridgeLoading 1 platforms...
29/8/2021 10:01:03Camera FFmpeg BridgeCamera FFmpeg[Back Yard] Configuring cached bridged accessory...
29/8/2021 10:01:03Camera FFmpeg BridgeBridge is running on port 51826.
29/8/2021 10:01:04Camera FFmpeg BridgeCamera FFmpegERROR[Back Yard] Failed to fetch snapshot.
29/8/2021 10:01:15Camera FFmpeg BridgeCamera FFmpegERROR[Back Yard] Failed to fetch snapshot.
29/8/2021 10:01:23Camera FFmpeg BridgeCamera FFmpegERROR[Back Yard] Failed to fetch snapshot.
29/8/2021 10:01:49Camera FFmpeg BridgeConfiguration change
29/8/2021 10:01:49cameraffmpegbridge stopping
29/8/2021 10:01:54Camera FFmpeg Bridge starting
29/8/2021 10:02:01Camera FFmpeg BridgeLoaded plugin 'homebridge-camera-ffmpeg'
29/8/2021 10:02:01Camera FFmpeg BridgeLoading 1 platforms...
29/8/2021 10:02:01Camera FFmpeg BridgeCamera FFmpeg[Back Yard] Configuring cached bridged accessory...
29/8/2021 10:02:02Camera FFmpeg BridgeBridge is running on port 51826.
29/8/2021 10:02:02Camera FFmpeg BridgeCamera FFmpegERROR[Back Yard] Failed to fetch snapshot.
29/8/2021 10:02:09Camera FFmpeg BridgeCamera FFmpegERROR[Back Yard] Failed to fetch snapshot.
29/8/2021 10:02:29Camera FFmpeg BridgeConfiguration change
29/8/2021 10:02:29cameraffmpegbridge stopping
29/8/2021 10:02:34Camera FFmpeg Bridge starting
29/8/2021 10:02:41Camera FFmpeg BridgeLoaded plugin 'homebridge-camera-ffmpeg'
29/8/2021 10:02:41Camera FFmpeg BridgeLoading 1 platforms...
29/8/2021 10:02:41Camera FFmpeg BridgeCamera FFmpegWARNING[Back Yard] The source for this camera is missing "-i", it is likely misconfigured.
29/8/2021 10:02:41Camera FFmpeg BridgeCamera FFmpeg[Back Yard] Configuring cached bridged accessory...
29/8/2021 10:02:41Camera FFmpeg BridgeBridge is running on port 51826.
29/8/2021 10:02:42Camera FFmpeg BridgeCamera FFmpegERROR[Back Yard] Failed to fetch snapshot.
29/8/2021 10:02:48Camera FFmpeg BridgeCamera FFmpegERROR[Back Yard] Failed to fetch snapshot.
29/8/2021 10:03:11Camera FFmpeg BridgeConfiguration change
29/8/2021 10:03:11cameraffmpegbridge stopping
29/8/2021 10:03:16Camera FFmpeg Bridge starting
29/8/2021 10:03:23Camera FFmpeg BridgeLoaded plugin 'homebridge-camera-ffmpeg'
29/8/2021 10:03:23Camera FFmpeg BridgeLoading 1 platforms...
29/8/2021 10:03:23Camera FFmpeg BridgeCamera FFmpegWARNING[Back Yard] The source for this camera is missing "-i", it is likely misconfigured.
29/8/2021 10:03:23Camera FFmpeg BridgeCamera FFmpeg[Back Yard] Configuring cached bridged accessory...
29/8/2021 10:03:23Camera FFmpeg BridgeBridge is running on port 51826.
29/8/2021 10:03:23Camera FFmpeg BridgeCamera FFmpegERROR[Back Yard] Failed to fetch snapshot.
29/8/2021 10:03:49Camera FFmpeg BridgeCamera FFmpegERROR[Back Yard] Failed to fetch snapshot.
29/8/2021 10:03:52Camera FFmpeg BridgeCamera FFmpegERROR[Back Yard] Failed to fetch snapshot.
29/8/2021 10:04:31Camera FFmpeg BridgeConfiguration change
29/8/2021 10:04:31cameraffmpegbridge stopping
29/8/2021 10:04:36Camera FFmpeg Bridge starting
29/8/2021 10:04:42Camera FFmpeg BridgeLoaded plugin 'homebridge-camera-ffmpeg'
29/8/2021 10:04:42Camera FFmpeg BridgeLoading 1 platforms...
29/8/2021 10:04:42Camera FFmpeg BridgeCamera FFmpegWARNING[Back Yard] The source for this camera is missing "-i", it is likely misconfigured.
29/8/2021 10:04:42Camera FFmpeg BridgeCamera FFmpeg[Back Yard] Configuring cached bridged accessory...
29/8/2021 10:04:43Camera FFmpeg BridgeBridge is running on port 51826.
29/8/2021 10:04:43Camera FFmpeg BridgeCamera FFmpegERROR[Back Yard] Failed to fetch snapshot.
29/8/2021 10:08:08Camera FFmpeg BridgeCamera FFmpegERROR[Back Yard] Failed to fetch snapshot.
29/8/2021 10:09:08Camera FFmpeg BridgeConfiguration change
29/8/2021 10:09:08cameraffmpegbridge stopping
29/8/2021 10:09:13Camera FFmpeg Bridge starting
29/8/2021 10:09:20Camera FFmpeg BridgeLoaded plugin 'homebridge-camera-ffmpeg'
29/8/2021 10:09:20Camera FFmpeg BridgeFailed to find plugin to handle accessory Back Yard
29/8/2021 10:09:20Camera FFmpeg BridgeBridge is running on port 51826.
29/8/2021 10:10:30Camera FFmpeg BridgeConfiguration change
29/8/2021 10:10:30cameraffmpegbridge stopping
29/8/2021 10:10:35Camera FFmpeg Bridge starting
29/8/2021 10:10:41Camera FFmpeg BridgeLoaded plugin 'homebridge-camera-ffmpeg'
29/8/2021 10:10:42Camera FFmpeg BridgeBridge is running on port 51826.
29/8/2021 19:07:20cameraffmpegbridge stopping
29/8/2021 19:07:53Camera FFmpeg Bridge starting
29/8/2021 19:08:14Camera FFmpeg BridgeWARNINGNo plugins installed.
29/8/2021 19:08:15Camera FFmpeg BridgeBridge is running on port 51826.
29/8/2021 19:08:21Camera FFmpeg BridgeConfiguration change
29/8/2021 19:08:21cameraffmpegbridge stopping
29/8/2021 19:08:28Camera FFmpeg Bridge starting
29/8/2021 19:08:48Camera FFmpeg BridgeLoaded plugin 'homebridge-camera-ffmpeg'
29/8/2021 19:08:48Camera FFmpeg BridgeLoading 1 platforms...
29/8/2021 19:08:48Camera FFmpeg BridgeBridge is running on port 51826.
29/8/2021 19:12:45Camera FFmpeg BridgeConfiguration change
29/8/2021 19:12:45cameraffmpegbridge stopping
29/8/2021 19:12:50Camera FFmpeg Bridge starting
29/8/2021 19:12:56Camera FFmpeg BridgeLoaded plugin 'homebridge-camera-ffmpeg'
29/8/2021 19:12:56Camera FFmpeg BridgeLoading 1 platforms...
29/8/2021 19:12:56Camera FFmpeg BridgeCamera-ffmpeg[Camera Name] Configuring bridged accessory...
29/8/2021 19:12:57Camera FFmpeg BridgeBridge is running on port 51826.
29/8/2021 19:12:57Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:01Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:02Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:03Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:04Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:05Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:06Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:07Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:08Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:09Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:10Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:11Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:12Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:14Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:15Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:16Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:17Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:18Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:19Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:20Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:21Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:22Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:23Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:24Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:13:41Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:14:29Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:14:52Camera FFmpeg BridgeConfiguration change
29/8/2021 19:14:52cameraffmpegbridge stopping
29/8/2021 19:14:54ERRORError [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:712:16)
    at /usr/src/hub/services/socket.ts:64:29
    at new Promise (<anonymous>)
    at Socket.fetch (/usr/src/hub/services/socket.ts:50:16)
    at /usr/src/hub/services/ipc.ts:39:41
    at new Promise (<anonymous>)
    at HubIPC.fetch (/usr/src/hub/services/ipc.ts:35:16)
    at /usr/src/hub/services/monitor.ts:32:28
    at new Promise (<anonymous>)
    at Monitor (/usr/src/hub/services/monitor.ts:31:24)
    at Timeout._a [as _onTimeout] (/usr/src/hub/services/monitor.ts:75:26)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
29/8/2021 19:14:54Camera FFmpeg Bridge stopping
29/8/2021 19:15:08hub is running on port 80
29/8/2021 19:15:09Camera FFmpeg Bridge starting
29/8/2021 19:15:15Camera FFmpeg BridgeLoaded plugin 'homebridge-camera-ffmpeg'
29/8/2021 19:15:15Camera FFmpeg BridgeLoading 1 platforms...
29/8/2021 19:15:15Camera FFmpeg BridgeCamera-ffmpeg[Camera Name] Configuring cached bridged accessory...
29/8/2021 19:15:16Camera FFmpeg BridgeBridge is running on port 51826.
29/8/2021 19:15:16Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:18Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:20Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:21Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:22Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:23Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:24Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:25Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:26Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:27Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:28Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:29Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:30Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:31Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:32Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:36Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:37Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:38Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:39Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:40Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:42Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:43Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:44Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:45Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:46Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:47Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:48Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:49Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:50Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:51Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:52Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:53Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:54Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:56Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:57Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:15:57Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:19:35Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:26:16Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:27:43Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:27:53Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:27:55Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:27:56Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:27:57Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:27:57Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:27:58Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:27:59Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:27:59Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:28:00Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:28:00Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:28:00Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:28:00Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:28:00Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:28:01Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:28:01Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:28:01Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:28:02Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:28:02Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:30:37Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:35:39Camera FFmpeg BridgeCamera-ffmpegERROR[Camera Name] Failed to fetch snapshot.
29/8/2021 19:36:30Camera FFmpeg BridgeConfiguration change
29/8/2021 19:36:30cameraffmpegbridge stopping
29/8/2021 19:36:35Camera FFmpeg Bridge starting
29/8/2021 19:36:41Camera FFmpeg BridgeLoaded plugin 'homebridge-camera-ffmpeg'
29/8/2021 19:36:41Camera FFmpeg BridgeLoading 1 platforms...
29/8/2021 19:36:41Camera FFmpeg BridgeCamera FFmpeg[Camera Name] Configuring cached bridged accessory...
29/8/2021 19:36:41Camera FFmpeg BridgeCamera FFmpeg[Camara 01] Configuring bridged accessory...
29/8/2021 19:36:41Camera FFmpeg BridgeCamera FFmpeg[Camera Name] Removing bridged accessory...
29/8/2021 19:36:41Camera FFmpeg BridgeBridge is running on port 51826.
29/8/2021 19:36:52Camera FFmpeg BridgeCamera FFmpegERROR[Camara 01] Failed to fetch snapshot.
29/8/2021 19:36:54Camera FFmpeg BridgeCamera FFmpegERROR[Camara 01] Failed to fetch snapshot.
29/8/2021 19:36:55Camera FFmpeg BridgeCamera FFmpegERROR[Camara 01] Failed to fetch snapshot.
29/8/2021 19:36:56Camera FFmpeg BridgeCamera FFmpegERROR[Camara 01] Failed to fetch snapshot.
29/8/2021 19:36:57Camera FFmpeg BridgeCamera FFmpegERROR[Camara 01] Failed to fetch snapshot.
29/8/2021 19:36:57Camera FFmpeg BridgeCamera FFmpegERROR[Camara 01] Failed to fetch snapshot.
29/8/2021 19:36:57Camera FFmpeg BridgeCamera FFmpegERROR[Camara 01] Failed to fetch snapshot.
29/8/2021 19:36:58Camera FFmpeg BridgeCamera FFmpegERROR[Camara 01] Failed to fetch snapshot.
29/8/2021 19:36:58Camera FFmpeg BridgeCamera FFmpegERROR[Camara 01] Failed to fetch snapshot.
29/8/2021 19:36:58Camera FFmpeg BridgeCamera FFmpegERROR[Camara 01] Failed to fetch snapshot.
29/8/2021 19:36:59Camera FFmpeg BridgeCamera FFmpegERROR[Camara 01] Failed to fetch snapshot.
29/8/2021 19:37:00Camera FFmpeg BridgeCamera FFmpegERROR[Camara 01] Failed to fetch snapshot.
29/8/2021 19:37:01Camera FFmpeg BridgeCamera FFmpegERROR[Camara 01] Failed to fetch snapshot.
29/8/2021 19:37:02Camera FFmpeg BridgeCamera FFmpegERROR[Camara 01] Failed to fetch snapshot.
29/8/2021 19:37:03Camera FFmpeg BridgeCamera FFmpegERROR[Camara 01] Failed to fetch snapshot.
29/8/2021 19:37:04Camera FFmpeg BridgeCamera FFmpegERROR[Camara 01] Failed to fetch snapshot.
29/8/2021 19:38:30cameraffmpegbridge stopping
29/8/2021 19:38:47Camera FFmpeg Bridge starting
29/8/2021 19:39:08Camera FFmpeg BridgeWARNINGNo plugins installed.
29/8/2021 19:39:08Camera FFmpeg BridgeFailed to find plugin to handle accessory Camara 01
29/8/2021 19:39:09Camera FFmpeg BridgeBridge is running on port 51826.
29/8/2021 19:39:15Camera FFmpeg BridgeConfiguration change
29/8/2021 19:39:15cameraffmpegbridge stopping
29/8/2021 19:39:19ERRORError: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:839:20)
    at ChildProcess.target.send (internal/child_process.js:710:19)
    at /usr/src/hub/services/socket.ts:64:29
    at new Promise (<anonymous>)
    at Socket.fetch (/usr/src/hub/services/socket.ts:50:16)
    at /usr/src/hub/services/ipc.ts:39:41
    at new Promise (<anonymous>)
    at HubIPC.fetch (/usr/src/hub/services/ipc.ts:35:16)
    at /usr/src/hub/services/monitor.ts:32:28
    at new Promise (<anonymous>)
    at Monitor (/usr/src/hub/services/monitor.ts:31:24)
    at Timeout._a [as _onTimeout] (/usr/src/hub/services/monitor.ts:75:26)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
29/8/2021 19:39:19Camera FFmpeg Bridge stopping
29/8/2021 19:39:32hub is running on port 80
29/8/2021 19:39:33Camera FFmpeg Bridge starting
29/8/2021 19:39:54Camera FFmpeg BridgeLoaded plugin 'homebridge-camera-ffmpeg'
29/8/2021 19:39:54Camera FFmpeg BridgeLoading 1 platforms...
29/8/2021 19:39:54Camera FFmpeg BridgeBridge is running on port 51826.
29/8/2021 19:41:35Camera FFmpeg BridgeConfiguration change
29/8/2021 19:41:35cameraffmpegbridge stopping
29/8/2021 19:41:40Camera FFmpeg Bridge starting
29/8/2021 19:41:47Camera FFmpeg BridgeLoaded plugin 'homebridge-camera-ffmpeg'
29/8/2021 19:41:47Camera FFmpeg BridgeBridge is running on port 51826.
29/8/2021 19:41:50Camera FFmpeg BridgeConfiguration change
29/8/2021 19:41:50cameraffmpegbridge stopping
29/8/2021 19:41:55Camera FFmpeg Bridge starting
29/8/2021 19:42:01Camera FFmpeg BridgeLoaded plugin 'homebridge-camera-ffmpeg'
29/8/2021 19:42:02Camera FFmpeg BridgeBridge is running on port 51826.
29/8/2021 19:45:06Camera FFmpeg BridgeConfiguration change
29/8/2021 19:45:06cameraffmpegbridge stopping
29/8/2021 19:45:11Camera FFmpeg Bridge starting
29/8/2021 19:45:18Camera FFmpeg BridgeLoaded plugin 'homebridge-camera-ffmpeg'
29/8/2021 19:45:19Camera FFmpeg BridgeBridge is running on port 51826.
29/8/2021 19:55:56Camera FFmpeg BridgeConfiguration change
29/8/2021 19:55:56cameraffmpegbridge stopping
29/8/2021 19:56:01Camera FFmpeg Bridge starting
29/8/2021 19:56:07Camera FFmpeg BridgeLoaded plugin 'homebridge-camera-ffmpeg'
29/8/2021 19:56:08Camera FFmpeg BridgeBridge is running on port 51826.

```
Show the Homebridge logs here.
Remove any sensitive information.     Like I say, I am new here, I dont know how to get other set of logs, sorry
```
**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token. Sorry again,  I dont know whwere to get it
```

**Screenshots:**

**Environment:**

I am using HOOBS BOX (STARTER KIT)  4.0.100

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Camera FFmpeg Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**: 

Thank you

**Comment by Richo005** [comment]
camera does not support rtsp
