### ISSUE TITLE
Suddenly Homebridge won't start with ffmpeg: says port 8080 in use.

### ISSUE THREAD

**Issue by jsiegenthaler** [Sunoo/homebridge-camera-ffmpeg#756]
**Describe The Problem:**

Today after a crashed Shelly1 device requiring a power off/on reboot, the ffmpeg plugin on Homebridge started causing problems

Homebridge would not start, showing the error in the log snippet below.
I changed the port to 8081, same error occurred.
I changed the port to 8082, then homebridge started up OK.
But now I have to change my device configs to move them all to port 8082 :(

Or do I?
So now both ports work:
http://192.168.0.171:8080/doorbell?Front%20Door
http://192.168.0.171:8082/doorbell?Front%20Door

This is wierd. Any idea why suddenly port 8080 would not be available, but then still works?

**To Reproduce:**

Unsure

**Logs:**

```
[8/27/2020, 16:37:18] Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at FfmpegPlatform.didFinishLaunching (/usr/lib/node_modules/homebridge-camera-ffmpeg/src/index.ts:346:14)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (/usr/lib/node_modules/homebridge/src/api.ts:251:10)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:158:14)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
```

**Homebridge Config:**

```json
        {
            "cameras": [
                {
                    "name": "Lounge",
                    "manufacturer": "Logitech Inc.",
                    "model": "QuickCam IM/Connect",
                    "serialNumber": "1234",
                    "firmwareRevision": "1.0",
                    "motion": true,
                    "motionTimeout": 1,
                    "doorbell": true,
                    "doorbellSwitch": true,
                    "switches": true,
                    "videoConfig": {
                        "source": "-f v4l2 -r 30 -s 640x480 -i /dev/video0",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "maxFPS": 25,
                        "oldvcodec": "h264_omx",
                        "vcodec": "h264",
                        "audio": false,
                        "debug": false
                    }
                },
                {
                    "name": "Front Door",
                    "manufacturer": "Jochen",
                    "model": "Camera-ffmpeg Video Doorbell",
                    "serialNumber": "1234",
                    "firmwareRevision": "1.0",
                    "motion": false,
                    "motionTimeout": 1,
                    "doorbell": true,
                    "doorbellSwitch": true,
                    "remoteHttpCommandToActivateDoorBell": "http://192.168.0.171:8082/doorbell?Front%20Door",
                    "switches": true,
                    "videoConfig": {
                        "source": "-re -ignore_loop 0 -i file:///home/pi/Public/fuo.gif",
                        "OLDstillImageSource": "-i file:///home/pi/Public/doorbell16x9.jpg",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "vcodec": "libx264",
                        "audio": false,
                        "packetSize": 1316,
                        "vflip": false,
                        "hflip": false,
                        "debug": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg",
            "porthttp": "8082"
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v12.18.3
* **NPM Version**: v6.14.8
* **Homebridge Version**: 
* **Homebridge Camera FFmpeg Version**: homebridge-camera-ffmpeg v3.0.1
* **Homebridge Config UI X Plugin Version**: homebridge-config-ui-x v4.27.0
* **Operating System**: Raspbian GNU/Linux Buster (10)

**Comment by Sunoo** [comment]
Literally any other process can grab a port before we get to it, there isn't much I can do about that. If we grabbed the port first, whatever other process is trying to use it would fail. The only real solution is to make sure both services are using different ports.

You could try to find out what grabbed it by running `sudo netstat -tulpn | grep :8080`.

**Comment by jsiegenthaler** [comment]
Tried that. 
pi@raspberrypi:~ $ sudo netstat -tulpn | grep :8080
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      536/motion

But isn't it wierd that ffmpeg reacts to commands now on both port 8080 and 8082?

**Comment by Sunoo** [comment]
Do you have two instances of Homebridge running?

**Comment by jsiegenthaler** [comment]
No i don^t.
I'm a homebridge ffmpeg newbie so bear with me if I've misunderstood or stuffed up something
I found a clue: I can view my USB webcam using http://192.168.0.171:8080/. It appears as a live video stream from Motion 4.1.1
But I cannot get it to show in Homekit any more

I've turned on debugging in ffmpeg plugin and get the following:

`8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] Video stream requested: 1920 x 1080, 30 fps, 802 kbps
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] Starting video stream: 640 x 480, 25 fps, 802 kbps
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] Stream command: /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -re -f video4linux2 -i /dev/video0 -an -sn -dn -codec:v h264_omx -pix_fmt yuv420p -color_range mpeg -r 25 -f rawvideo -filter:v scale='min(640,iw)':'min(480,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -b:v 802k -payload_type 99 -ssrc 5787204 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params tEqaamT9srYB+FdEm04srwPGQRZOVbm65qmJJTwt srtp://192.168.0.212:55858?rtcpport=55858&pkt_size=1316 -vn -sn -dn -codec:a libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -ac 1 -payload_type 110 -ssrc 922336 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params oUs+dFz+BqslDiD6LwGUj1ICnNL74uIBVVoWyzt/ srtp://192.168.0.212:61792?rtcpport=61792&pkt_size=188 -loglevel level+verbose
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] [info] ffmpeg version 4.2.2-d1e8be3 Copyright (c) 2000-2019 the FFmpeg developers
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] [info]   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] [info]   configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] 
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] [info]   libavutil      56. 31.100 / 56. 31.100
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] [info]   libavcodec     58. 54.100 / 58. 54.100
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] [info]   libavformat    58. 29.100 / 58. 29.100
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] [info]   libavdevice    58.  8.100 / 58.  8.100
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] [info]   libavfilter     7. 57.100 /  7. 57.100
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] [info]   libswscale      5.  5.100 /  5.  5.100
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] [info]   libswresample   3.  5.100 /  3.  5.100
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] [info]   libpostproc    55.  5.100 / 55.  5.100
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] 
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] [video4linux2,v4l2 @ 0x39e6220] [verbose] fd:3 capabilities:85200001
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] [video4linux2,v4l2 @ 0x39e6220] [verbose] Querying the device for the current frame size
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] [video4linux2,v4l2 @ 0x39e6220] [verbose] Setting frame size to 640x480
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] 
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] [error] /dev/video0: Device or resource busy
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] 
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] FFmpeg exited with code: 1 and signal: null (Error)
[8/28/2020, 21:16:33] [Camera FFmpeg] [Lounge] Stopped video stream.`

**Comment by Sunoo** [comment]
Video4Linux2 only allows one program to access a device at a time. If that other software is running and streaming your webcam, this plugin will be prevented from connecting to the camera.

**Comment by jsiegenthaler** [comment]
Thanks, that helped me understand. I stopped the motion service.

Now ffmpeg shows
[8/29/2020, 09:33:10] [Camera FFmpeg] [Lounge] Snapshot requested: 480 x 270
[8/29/2020, 09:33:10] [Camera FFmpeg] [Lounge] Sending snapshot: 480 x 270
[8/29/2020, 09:33:10] [Camera FFmpeg] [Lounge] Snapshot command: /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -f v4l2 -r 30 -s 640x480 -i /dev/video0 -frames:v 1 -filter:v scale='min(480,iw)':'min(270,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -f image2 -
[8/29/2020, 09:33:26] [Camera FFmpeg] [Lounge] Snapshot requested: 480 x 270
[8/29/2020, 09:33:26] [Camera FFmpeg] [Lounge] Sending snapshot: 480 x 270
[8/29/2020, 09:33:26] [Camera FFmpeg] [Lounge] Snapshot command: /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -f v4l2 -r 30 -s 640x480 -i /dev/video0 -frames:v 1 -filter:v scale='min(480,iw)':'min(270,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -f image2 -
[8/29/2020, 09:33:41] [Camera FFmpeg] [Lounge] Snapshot requested: 480 x 270
[8/29/2020, 09:33:41] [Camera FFmpeg] [Lounge] Sending snapshot: 480 x 270
[8/29/2020, 09:33:41] [Camera FFmpeg] [Lounge] Snapshot command: /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -f v4l2 -r 30 -s 640x480 -i /dev/video0 -frames:v 1 -filter:v scale='min(480,iw)':'min(270,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -f image2 -
[8/29/2020, 09:33:57] [Camera FFmpeg] [Lounge] Snapshot requested: 480 x 270
[8/29/2020, 09:33:57] [Camera FFmpeg] [Lounge] Sending snapshot: 480 x 270
[8/29/2020, 09:33:57] [Camera FFmpeg] [Lounge] Snapshot command: /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -f v4l2 -r 30 -s 640x480 -i /dev/video0 -frames:v 1 -filter:v scale='min(480,iw)':'min(270,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -f image2 -
[8/29/2020, 09:34:13] [Camera FFmpeg] [Lounge] Snapshot requested: 480 x 270
[8/29/2020, 09:34:13] [Camera FFmpeg] [Lounge] Sending snapshot: 480 x 270
[8/29/2020, 09:34:13] [Camera FFmpeg] [Lounge] Snapshot command: /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -f v4l2 -r 30 -s 640x480 -i /dev/video0 -frames:v 1 -filter:v scale='min(480,iw)':'min(270,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -f image2 -
[8/29/2020, 09:34:29] [Camera FFmpeg] [Lounge] Snapshot requested: 480 x 270
[8/29/2020, 09:34:29] [Camera FFmpeg] [Lounge] Sending snapshot: 480 x 270
[8/29/2020, 09:34:29] [Camera FFmpeg] [Lounge] Snapshot command: /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -f v4l2 -r 30 -s 640x480 -i /dev/video0 -frames:v 1 -filter:v scale='min(480,iw)':'min(270,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -f image2 -
[8/29/2020, 09:34:44] [Camera FFmpeg] [Lounge] Snapshot requested: 480 x 270
[8/29/2020, 09:34:44] [Camera FFmpeg] [Lounge] Sending snapshot: 480 x 270
[8/29/2020, 09:34:45] [Camera FFmpeg] [Lounge] Snapshot command: /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -f v4l2 -r 30 -s 640x480 -i /dev/video0 -frames:v 1 -filter:v scale='min(480,iw)':'min(270,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -f image2 -
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] Video stream requested: 1920 x 1080, 30 fps, 802 kbps
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] Starting video stream: 640 x 480, 25 fps, 802 kbps
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] Stream command: /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -f v4l2 -r 30 -s 640x480 -i /dev/video0 -an -sn -dn -codec:v h264 -pix_fmt yuv420p -color_range mpeg -r 25 -f rawvideo -filter:v scale='min(640,iw)':'min(480,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -b:v 802k -payload_type 99 -ssrc 4135032 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params Vq270rNzfKvaKeEg4LRBoj8zvps6z/rrdy9JnpO0 srtp://192.168.0.212:49268?rtcpport=49268&pkt_size=1316 -vn -sn -dn -codec:a libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -ac 1 -payload_type 110 -ssrc 4383502 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params xsGTZcw9zsCum7i9W+Yqxl4to686fDRy4aSUPc5l srtp://192.168.0.212:62556?rtcpport=62556&pkt_size=188 -loglevel level+verbose
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] [info] ffmpeg version 4.2.2-d1e8be3 Copyright (c) 2000-2019 the FFmpeg developers
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] [info]   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] [info]   configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] 
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] [info]   libavutil      56. 31.100 / 56. 31.100
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] [info]   libavcodec     58. 54.100 / 58. 54.100
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] [info]   libavformat    58. 29.100 / 58. 29.100
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] [info]   libavdevice    58.  8.100 / 58.  8.100
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] [info]   libavfilter     7. 57.100 /  7. 57.100
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] [info]   libswscale      5.  5.100 /  5.  5.100
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] [info]   libswresample   3.  5.100 /  3.  5.100
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] [info]   libpostproc    55.  5.100 / 55.  5.100
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] 
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] [video4linux2,v4l2 @ 0x2a0e2c0] [verbose] fd:3 capabilities:85200001
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] 
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] [video4linux2,v4l2 @ 0x2a0e2c0] [warning] The driver does not permit changing the time per frame
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] [video4linux2,v4l2 @ 0x2a0e2c0] [warning] Time per frame unknown
[8/29/2020, 09:34:52] [Camera FFmpeg] [Lounge] 
[8/29/2020, 09:34:58] [Camera FFmpeg] [Lounge] [info] Input #0, video4linux2,v4l2, from '/dev/video0':
[8/29/2020, 09:34:58] [Camera FFmpeg] [Lounge] [info]   Duration: N/A, start: 146715.599958, bitrate: N/A
[8/29/2020, 09:34:58] [Camera FFmpeg] [Lounge] 
[8/29/2020, 09:34:58] [Camera FFmpeg] [Lounge] [info]     Stream #0:0: Video: mjpeg (Baseline), 1 reference frame, yuvj422p(pc, bt470bg/unknown/unknown, center), 640x480, 1000k tbr, 1000k tbn, 1000k tbc
[8/29/2020, 09:34:58] [Camera FFmpeg] [Lounge] [verbose] Matched encoder 'libx264' for codec 'h264'.
[8/29/2020, 09:34:58] [Camera FFmpeg] [Lounge] 
[8/29/2020, 09:34:58] [Camera FFmpeg] [Lounge] [info] Output #1, rtp, to 'srtp://192.168.0.212:62556?rtcpport=62556&pkt_size=188':
[8/29/2020, 09:34:58] [Camera FFmpeg] [Lounge] [error] Output file #1 does not contain any stream
[8/29/2020, 09:34:58] [Camera FFmpeg] [Lounge] [AVIOContext @ 0x2a17ee0] [verbose] Statistics: 0 seeks, 0 writeouts
[8/29/2020, 09:34:58] [Camera FFmpeg] [Lounge] 
[8/29/2020, 09:34:58] [Camera FFmpeg] [Lounge] FFmpeg exited with code: 1 and signal: null (Error)
[8/29/2020, 09:34:58] [Camera FFmpeg] [Lounge] Stopped video stream.

**Comment by Sunoo** [comment]
It looks like you probably have audio enabled for a camera that doesn’t provide audio.

**Comment by jsiegenthaler** [comment]
Thanks. That solved it. I set audio=false, and now I have live pictures again.
The root cause was motion 4.1.1 taking over port 8080, blocking ffmpeg from accessing the stream
All subsequent issues were caused by me playing with the config.

The only thing left to do is ensure motion 4.1.1 doesn't auto-start on reboot.

Thanks heaps for your support, I'll close the ticket.
