### ISSUE TITLE
HomeBridge version of >=1.0.0 

### ISSUE THREAD

**Issue by househippo** [Sunoo/homebridge-camera-ffmpeg#810]
I'm running: 
homebrideg-camera-ffmpeg version:  v3.0.3
homebridge version: 1.2.3

I'm getting the below error on homebridge start.
Where is the plugin getting the homebridge version info from for the check?

**Logs:**

[9/24/2020, 21:04:53] ERROR LOADING PLUGIN homebridge-camera-ffmpeg:
[9/24/2020, 21:04:53] Error: Plugin /usr/lib/node_modules/homebridge-camera-ffmpeg requires a HomeBridge version of >=1.0.0 which does not satisfy the current HomeBridge version of 0.4.50. You may need to upgrade your installation of HomeBridge.
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:56:11)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:153:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:145:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:32:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
[9/24/2020, 21:04:53] ====================
Error: The requested platform 'Camera-ffmpeg' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:27:21)

**Comment by Sunoo** [comment]
You are running Homebridge 0.4.50, which is quite old and has not been supported by this plugin for some time.

**Comment by househippo** [comment]
The UI is saying I'm running 1.2.3 ... is there a CLI to double check?

![Screen Shot 2020-09-24 at 9 30 44 PM](https://user-images.githubusercontent.com/4956099/94219817-4e9e0e80-fead-11ea-9d4a-4e8857a0f852.png)

**Comment by Sunoo** [comment]
It’s the second line of the log you shared in your first message.

**Comment by donavanbecker** [comment]
Must be running 2 different instances of homebridge..?
