### ISSUE TITLE
Capture Notification Pictures...

### ISSUE THREAD

**Issue by JimmyEyeball** [Sunoo/homebridge-camera-ffmpeg#852]
I have the plugin working perfectly first of all my setup is that I have an RF Door Bell + Sonoff Bridge set as a Single switch triggering the Doorbell Trigger in the Plugin ....... Hopefully, that makes sense... All works Perfectly. I get an iOS notification on all my devices I can see the small Pic in the notifications but if I click the notification it takes me straight to the live feed all working but a lot of the time whoever was there is gone. Some way to hold or store the pics would be ideal to check..

I know that there used to be a Google Drive option that was removed but is there any way for the phone to save the pic or something???

**Comment by Sunoo** [comment]
There is currently no way to do that with the plugin. I honestly had no intention to add it either, but I have had a few people ask now. If I can come up with a reasonable way to allow some other plugin to hook in and handle that, I may implement it that way.

**Comment by JimmyEyeball** [comment]
Would be much appreciated I keep my eye out for updates thank you...

**Comment by NorthernMan54** [comment]
@Sunoo I’m still using the google option, and have changed it use photos rather than drive.

If we can come up with a simple hook, I can make my code a plugin for the plugin.  The API would need to include the picture object, meta data about the picture, and a configuration object containing the google credentials.

Is it feasible to include the package name as a config item?  Then if set, invoke the hook. ( require the package and call the API )

Am thinking the end user would need to install the package by hand

**Comment by Sunoo** [comment]
@NorthernMan54 How does your support currently work? Does it just save the image every time HomeKit asks for a still, or does it try to be smarter than that?

It is possible to have a Homebridge plugin that doesn’t expose an accessory, but still has its own configuration object, which is how I’ve supported other means of triggering motion alerts. I was imagining that would be the way I would do this as well, especially since that would still allow installation from Config UI X.

I haven’t fully thought this through yet, but I would imagine something like emitting an event containing the picture data as well as the metadata about which camera, etc. Then the storage plugin would hook that emitter, and do whatever it wanted with the result.

Also, at the risk of scope creep, does anyone think there is any reason to provide support for video recordings as well in whatever we do here? I have been asked for that as well in the past, but that feels significantly more complicated.

If video was something we wanted to include, the emitter event would probably have to send motion/doorbell events as well as the URL to pull the video from.

**Comment by NorthernMan54** [comment]
As far as I’m aware Homebridge and hap-node have runtime isolation between plugins, so one can’t see events from another.  But thru some magic installing thru config-ui may be doable, and could require sending beer to Australia to help it along.

The old version was coded as part of the snapshot request handler, and just passed the object to google as well as send the image to HomeKit.  Downside of this approach is that google is flooded with images if you have the camera visible in the home app, and it is refreshing the still.  I’m still using the today, as the flooding is bearable for me.  Having an optional requires statement and api call is what I was envisioning in that section of code is what I was envisioning.

Using node-red, I’m also triggering video recordings based on motion events and sending those to google as well.  I have it capturing 60 seconds of video starting 20 seconds before the motion sensor was triggered. ( in my spare time I also built a time machine ).  I found this gives more detail around what triggered the sensor.  ( I also time compress the video so you don’t have to sit thru nothing happening ).

Realize that video is a complex option, but snapshots are pretty straight forward.  And for the plugin calling plugin model we would need to just make it a general pattern so other storage options could be supported

**Comment by Sunoo** [comment]
You can use Homebridge’s `API` emitter to send your own events, and other plugins will be able to see them. This is likely the way I’d go, but I’d have to give it some thought. It also wouldn’t be too hard to have the image handling plugin run a small HTTP server or similar and get events that way, but that adds a decent amount of unnecessary complexity and overhead.

Ideally I’d like to avoid the flood of images, which would likely require some slight reworking of this plugin. I have some very rough ideas, but I’d have to think on it some more. Especially since a motion event has every device fetch a snapshot, so you’d currently end up with a lot of duplicate images. Some light caching (which would be good to add to this plugin anyways) could get that down to one though.

I think I was probably getting ahead of myself with worrying about video, so I think I’ll set that whole issue aside for now and focus on stills.

**Comment by NorthernMan54** [comment]
Had a little bit of an inspiration this weekend, and figured out how to only trigger photo uploads when motion triggers the snapshot request ( or pretty close to it ) without mucking about in the internals of homebridge.  With the approach I took, I just flipped a flag within ffmpeg to tell it to upload to google the next snapshot request.  And wired 'dummy' switch function to flip the flag when a motion or doorbell event is triggered.  Worked really well

Next step is figure out an easy way to have a plugin call a plugin.

**Comment by HSkul** [comment]
If this is being considered for implementation (I really liked the option to upload images to Google) would it be possible to implement a switch that turns upload on/off?  That way the folks that use this for a security camera could automate it such as it only uploads when no one is at home (or when on vacation or during the night, or ...).  It might cut down some unnecessary uploads.  I did have a flood of images ending up in Google drive due to incorrect setup of my PIR sensor so I can see that being an issue.  Thanks for a great plugin.

**Comment by Sunoo** [comment]
@HSkul If implemented the way I am thinking of, where a separate plugin would handle the upload, I think it would be more appropriate for the second plugin to handle exposing a switch to disable that, if desired.

**Comment by Sunoo** [comment]
I’ve recently given some more thought to this, and partially as a result, I plan to soon add a brief cache of snapshots, so a single motion alert doesn’t result in a pile of requests for images slamming the camera all at once. That would also prevent getting multiple copies of the same image uploaded.

As for how best to handle passing the image to the other plugin, the best idea I’ve had so far is using HTTP, as abusing the API emitter would likely not work if the user has enabled the new child bridges feature in Homebridge. Using HTTP could also possibly close another request I’ve had: https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/929#issuecomment-782941672

@NorthernMan54 Unless you’ve come up with a better way to pass data between plugins, I don’t hate the idea of using HTTP. This plugin already is using HTTP as a means of triggering motion, so there is some precedent. I don’t think MQTT would really work for this, but I really don’t want to require users to set up a broker just to pass data between two plugins anyways.

**Comment by bluntiless** [comment]
Hi @NorthernMan54 

I had this working perfectly for a long time, but recently I am getting this error and I don't know what is causing it. 

Here is the console output:

[4/7/2021, 16:23:09] [Camera-ffmpeg] Error: Error: Can't access to Google Photos
    at GPhotos.<anonymous> (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/upload-gphotos/lib/index.js:167:39)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/upload-gphotos/lib/index.js:4:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Any help or advice would be greatly appreciated.

**Comment by NorthernMan54** [comment]
@bluntiless I found that something had changed on the google photos side about a month ago.  To restore service I had to make a couple of updates and am currently using this version

npm install -g NorthernMan54/homebridge-camera-ffmpeg#Google-Photos

**Comment by bluntiless** [comment]
Hi again NorthernMan54

I installed the version above and restarted homebridge and it worked for about 1 minute. But unfortunately it stopped working after that. It seems to take the snapshot but there is no attempt to upload in the terminal logs anymore. Not sure what has gone wrong. 
Do you have any ideas?

This is what the Terminal log display when it worked for a moment and then once it failed to upload.

Any advice would be greatly appreciated.

[8/7/2021, 11:48:00] [Camera-ffmpeg] Uploaded GARAGE_STORAGE_8_7_2021__11:47:57.jpeg
[8/7/2021, 11:48:00] [Camera-ffmpeg] id undefined
[1628333281381] INFO (937 on raspberrypi): incoming request
    req: {
      "method": "GET",
      "url": "/api/server/qrcode.svg",
      "hostname": "19x.xxx.4.xx:8581",
      "remoteAddress": "::ffff:192.168.4.22",
      "remotePort": 57447
    }
    reqId: 505
[1628333281424] INFO (937 on raspberrypi): request completed
    res: {
      "statusCode": 200
    }
    responseTime: 40.553282022476196
    reqId: 505
[8/7/2021, 11:48:01] [Camera-ffmpeg] Snapshot from INTERNAL FRONT DOOR at 480:270
[8/7/2021, 11:48:01] [Camera-ffmpeg] Snapshot from FRONT DRIVE RIGHT at 480:270
[8/7/2021, 11:48:06] [Camera-ffmpeg] Snapshot from FRONT DRIVE at 480:270
[8/7/2021, 11:48:08] [Camera-ffmpeg] Snapshot from TV ROOM at 480:270
[8/7/2021, 11:48:14] [Camera-ffmpeg] Snapshot from INTERNAL FRONT DOOR at 480:270
[8/7/2021, 11:48:14] [Camera-ffmpeg] Snapshot from FRONT DRIVE RIGHT at 480:270
[8/7/2021, 11:48:18] [Camera-ffmpeg] Snapshot from TV ROOM at 480:270
[8/7/2021, 11:48:27] [Camera-ffmpeg] Snapshot from INTERNAL FRONT DOOR at 480:270
[8/7/2021, 11:48:27] [Camera-ffmpeg] Snapshot from FRONT DRIVE RIGHT at 480:270
[8/7/2021, 11:48:29] [Camera-ffmpeg] Snapshot from TV ROOM at 480:270
[8/7/2021, 11:48:29] [Camera-ffmpeg] Snapshot from FRONT DRIVE at 480:270

**Comment by NorthernMan54** [comment]
It is still working fine for me, but since Google started charging for storage on June 1, I found that it stops when I run out of the basic 15Gb allotment.

My test from this am

```
[Camera-ffmpeg] Snapshot from Eufy Porch at 480:270
[Camera-ffmpeg] Snapshot from Eufy Porch at 1280:720
[Camera-ffmpeg] Queue 144595 Eufy_Porch_8_8_2021__9:26:22_AM.jpeg
[Camera-ffmpeg] Uploaded Eufy_Porch_8_8_2021__9:26:22_AM.jpeg
[Camera-ffmpeg] id undefined
```

And I checked, and the photo was uploaded

**Comment by NorthernMan54** [comment]
Another tip, I use a separate google account for just my cameras, so the 15Gb allocation is just used by them and not me personally.

**Comment by bluntiless** [comment]
I am so sorry, for some reason all the automations I had previously set up were disabled and not triggering the motion sensors for capturing photos. 
So I have it working and uploading correctly again with new automations for each motion sensor. 
It used to upload every snapshot including every time you open the Home App on iOS or OSX which was why I thought it had stopped working. 
So this version is actually much better as it will prevent the google photo storage from being wasted with non-motion activated pictures. Thank you very much for your work on this.

KR

**Comment by NorthernMan54** [comment]
I had made the change to only upload ones triggered by a motion sensor sometime lat year, I had gotten tired of the spurious uploads triggered by opening the app.

**Comment by bluntiless** [comment]
Very good idea and thanks again for all your work on this project!👍🏾

**Comment by bluntiless** [comment]
Hi again @NorthernMan54 

I am occassionly getting this error:

[9/14/2021, 09:39:48] [Camera-ffmpeg] Error: TypeError: text is not iterable
    at Keyboard.type (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/puppeteer-core/src/common/Input.ts:237:24)
    at ElementHandle.type (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/puppeteer-core/src/common/JSHandle.ts:649:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.signinViaPuppeteer (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/upload-gphotos/lib/signin_via_puppeteer.js:46:9)
    at GPhotos.signin (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/upload-gphotos/lib/GPhotos.js:27:13)
    at /usr/local/lib/node_modules/homebridge-camera-ffmpeg/gphoto.js:47:11
[9/14/2021, 09:40:02] [Camera-ffmpeg] Error: TypeError: text is not iterable
    at Keyboard.type (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/puppeteer-core/src/common/Input.ts:237:24)
    at ElementHandle.type (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/puppeteer-core/src/common/JSHandle.ts:649:31)

It seems to correct itself without me doing anything, but it is unpredictable and has been like this since yesterday. Any idea how I can fix this?

Thanks in advance.

**Comment by NorthernMan54** [comment]
@bluntiless I am also seeing the same issue, and it appears to be in the 'upload-gphotos' package I use to actually upload the photos.  I had just checked on GitHub, and the package maintainer has now archived the package so he doesn't have a fix.  I have found that I do need to restart homebridge when this starts occurring to restore service.

I'm going to need to take over the package, and try to resolve the issue

**Comment by bluntiless** [comment]
@NorthernMan54 thanks for the info. Out of interest, which version of Homebridge are you currently using? As I updated to the latest version yesterday and I am getting lots more errors now with Cameras and snapshots. 
For e.g.
The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.
[9/15/2021, 17:23:53] [homebridge-camera-ffmpeg] Error: TypeError: text is not iterable

**Comment by bluntiless** [comment]
Also seeing this:
(node:24821) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:24821) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit

**Comment by NorthernMan54** [comment]
@bluntiless As I have a large number of devices and technology I run multiple RPI's with homebridge, and so software currency sometimes gets trumped by stability.  So the instance running camera-ffmpeg is running 1.3.0-beta.58

`(node:24821) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit`

For this error, are you sure it's camera-ffmpeg triggering it ?  I get that sometimes from the Insteon plugin

`The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.`

That was an enhancement from the later homebridge versions, so that slow devices were identified and reported.  If your cameras are slow to produce a snapshot it will trigger.

**Comment by Sunoo** [comment]
I’m not sure NorthernMan’s version is impacted, but the EventEmitter issue warning is a known issue when you have a large number of cameras. I have plans to fix it, but it hasn’t been a very high priority for me, since there is no actual memory leak, just the warning.

**Comment by bluntiless** [comment]
Hi @Sunoo and @NorthernMan54, thanks for the information.
I am now unable it seems, to reset the Error: TypeError: text is not iterable by restarting Homebridge. 
I had updated Homebridge to the latest version and also downgraded back to 1.3.0 (couldn't find beta.58), which I am currently on now. 
I have also put the cameras in a Child Bridge to see if that would help with the image snapshot handler is slow to respond issue, which does seem to have stopped the message from appearing. 
Unfortunately stuck on  Error: TypeError: text is not iterable and no uploads to Google Photos anymore.

**Comment by NorthernMan54** [comment]
Do you have available storage on gphotos?  I ran out once already, and needed to cleanup.  I don’t recall the message though.

**Comment by bluntiless** [comment]
Yes I have plenty of storage available.

**Comment by bluntiless** [comment]
Despite restarting homebridge numerous times, it still fails with this error:

[9/16/2021, 16:42:32] [Camera-ffmpeg] Snapshot from FRONT DRIVE at 1280:720
[9/16/2021, 16:42:32] [Camera-ffmpeg] Snapshot from FRONT DRIVE RIGHT at 1280:720
[9/16/2021, 16:42:35] [Camera-ffmpeg] Queue 63573 FRONT_DRIVE_RIGHT_9_16_2021__16:42:35.jpeg
[9/16/2021, 16:42:35] [Camera-ffmpeg] Queue 57819 FRONT_DRIVE_9_16_2021__16:42:35.jpeg
[FRONT DRIVE RIGHT 7442] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.[9/16/2021, 16:44:09] [Camera-ffmpeg] Error: TypeError: text is not iterable
    at Keyboard.type (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/puppeteer-core/src/common/Input.ts:237:24)
    at ElementHandle.type (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/puppeteer-core/src/common/JSHandle.ts:649:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.signinViaPuppeteer (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/upload-gphotos/lib/signin_via_puppeteer.js:46:9)
    at GPhotos.signin (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/upload-gphotos/lib/GPhotos.js:27:13)
    at /usr/local/lib/node_modules/homebridge-camera-ffmpeg/gphoto.js:47:11

**Comment by NorthernMan54** [comment]
Looking at the stack trace you provided

This is a failure while attempting to login, and it appears to be having problems getting the gphotos login page 'https://photos.google.com/login' and errors before entering your password and while entering your username.

```
at Object.signinViaPuppeteer (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/upload-gphotos/lib/signin_via_puppeteer.js:46:9)
at GPhotos.signin (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/upload-gphotos/lib/GPhotos.js:27:13)
```

**Comment by bluntiless** [comment]
I'm sorry for wasting your time, it was my config.js!  When you said that it is failing whilst attempting to login, that made me think. In trying to resolve this problem I had updated Homebridge-camera-ffmpeg to a newer version which removed all the login credentials for gphotos login! Thank you again for all your assistance.

**Comment by JimmyEyeball** [comment]
Sorry if I have completely missed something but I cant see no reference to this in the readme on how to add this to the config. could someone post and example config of how they have this setup as I say ideally I want to capture a pic every time the door bell switch is activated.

Thank you in advance...

**Comment by bluntiless** [comment]
Hi@JimmyEyeball,

Can you tell me if you have @NorthernMan54's version of homebridge-camera-ffmpeg installed? If so I can send you my config.js with how to complete your credentials for Google photos uploading.

**Comment by JimmyEyeball** [comment]
https://github.com/Sunoo/homebridge-camera-ffmpeg#readme

![image](https://user-images.githubusercontent.com/50030249/135724182-5faf483e-0384-4441-8c9f-3d3a8de1e50b.png)

**Comment by bluntiless** [comment]
Ok so you need to downgrade and use @NorthernMan54's version of Homebridge-camera-ffmpeg v1.2.1.

npm install -g NorthernMan54/homebridge-camera-ffmpeg#Google-Photos

**Comment by JimmyEyeball** [comment]
This was just a test run on my pi but I will be installing it on my Windows HB but getting the errors below...

Is this also and old version of this plugin? will this cause any issues?


sudo npm install -g NorthernMan54/homebridge-camera-ffmpeg#Google-Photos --unsafe-perm



npm ERR! code 128
npm ERR! Command failed: git clone --depth=1 -q -b Google-Photos git://github.com/NorthernMan54/homebridge-camera-ffmpeg.git /root/.npm/_cacache/tmp/git-clone-056d637f
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-056d637f': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-10-03T11_53_25_335Z-debug.log

**Comment by bluntiless** [comment]
I have homebridge running on a Pi 2 with homebridge version 1.3.2 installed and it has no issues with @NorthernMan54's version.

The errors you are getting appear to be due incorrect permissions when installing. It might be how you are logged in.

**Comment by HSkul** [comment]
> sudo npm install -g NorthernMan54/homebridge-camera-ffmpeg#Google-Photos --unsafe-perm
> 
> npm ERR! code 128 npm ERR! Command failed: git clone --depth=1 -q -b Google-Photos git://github.com/NorthernMan54/homebridge-camera-ffmpeg.git /root/.npm/_cacache/tmp/git-clone-056d637f npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-056d637f': Permission denied npm ERR!
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /root/.npm/_logs/2021-10-03T11_53_25_335Z-debug.log

Getting the same error on my Pi2 with 1.3.5 installed when I try to install the Google photos version.  Is it possible some permissions are corrupt?  I'm also having issues with public key not available for deb.nodesource.com.

 H

**Comment by HSkul** [comment]
Are there anywhere updated directions on how to get the upload to work with Google Photos, both in terms of how the account needs to be set up and what needs to be done for credentials?
I've finally managed to install everything, added the login information to config.json, allowed less secure app access, created the credentials, ran the quickstart.js and copied the token but I get this error right after starting Homebridge:

(node:10897) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector `input[type="password"]` failed: timeout 30000ms exceeded
    at new WaitTask (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/puppeteer-core/src/common/DOMWorld.ts:776:28)
    at DOMWorld.waitForSelectorInPage (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/puppeteer-core/src/common/DOMWorld.ts:628:22)
    at Object.internalHandler.waitFor (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/puppeteer-core/src/common/QueryHandler.ts:78:19)
    at DOMWorld.waitForSelector (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/puppeteer-core/src/common/DOMWorld.ts:486:25)
    at Frame.waitForSelector (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/puppeteer-core/src/common/FrameManager.ts:1159:47)
    at Page.waitForSelector (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/puppeteer-core/src/common/Page.ts:1971:29)
    at Object.signinViaPuppeteer (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/upload-gphotos/lib/signin_via_puppeteer.js:47:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at GPhotos.signin (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/upload-gphotos/lib/GPhotos.js:27:13)
    at /usr/lib/node_modules/homebridge-camera-ffmpeg/gphoto.js:30:7

  Then I get the following error  each time Homebridge tries to upload an image (everything else works):

[Camera-ffmpeg] Error: TypeError: text is not iterable
    at Keyboard.type (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/puppeteer-core/src/common/Input.ts:237:24)
    at ElementHandle.type (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/puppeteer-core/src/common/JSHandle.ts:649:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.signinViaPuppeteer (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/upload-gphotos/lib/signin_via_puppeteer.js:46:9)
    at GPhotos.signin (/usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/upload-gphotos/lib/GPhotos.js:27:13)
    at /usr/lib/node_modules/homebridge-camera-ffmpeg/gphoto.js:47:11

  I suspect this has something to do with improper credentials.  The Google Photos account is completely empty so space is not an issue.

  Thanks,

  H

**Comment by HSkul** [comment]
Quick question. Do I need to have the desktop environment running when using the Google upload feature?  As I’m trying to get the upload to work and reading up on upload-gphoto it mentioned using a browser for authentication (and upload?). 
  Thanks and Merry Christmas. 
  
  H

**Comment by HSkul** [comment]
Any suggestion on how to make google-photos version work?  After trying multiple things I still get the timeout error after 30s.  With the current setup Homebridge reboots every time on the error.
  Setup:

Raspberry Pi 2 running Buster
Node.js:  17.4.0
Npm:      8.3.2
Homebridge:  1.4.0

 First I installed chromium-browser (via apt-get) and it installed version 92.0.4515.98.  Since puppeteer 7.1.0 (installed with the plugin) calls for 90.0.4403.0 I installed 90.0.4430.212 but no change.  As I get the timeout error each time.

  Note that I can see that the chromium is being called as I see 5 (or 6) instances of chromium running just as the error is thrown but I guess the login is never successful or it is not returned to puppeteer within 30s.

  How many instances of chromium should show up?  Is it possible that there is something wrong with my wifi setup (DHCP) that is causing this?  The connection speeds seems to be just fine.  I've run the chromium browser on a remote display (via ssh -X session) and successfully logged into Google albeit it was very slow.

  Thanks,

  H

**Comment by NorthernMan54** [comment]
As the google photos api is not well supported and has proven to be problematic I’m considering moving it to amazon photos.

currently for me it hangs about once a week, and the package I used to connect to google no longer has support.  So it is on a death watch.

**Comment by HSkul** [comment]
Understood. I’m assuming then that something like gPhotoSpy has similar issues?   Too bad since adding values to Gogglesheets seems to work so well (from Python).

  Thanks for all your work on this.

  H

**Comment by NorthernMan54** [comment]
Just doing some google research, and found this package https://github.com/gphotosuploader/gphotos-uploader-cli

And added it to my node-red motion detection flow beside the existing google-photos module, and so far it seems pretty solid.  I'm going to let it run for a few weeks, and see how it goes over time.

**Comment by HSkul** [comment]
> Just doing some google research, and found this package https://github.com/gphotosuploader/gphotos-uploader-cli
> 
> And added it to my node-red motion detection flow beside the existing google-photos module, and so far it seems pretty solid. I'm going to let it run for a few weeks, and see how it goes over time.

 Sooooo, is it working?  I can beta test as I have a new in the box RPi 4 8GB that is begging me to do something with it.

  Thanks again for moving this forward.

  H

**Comment by NorthernMan54** [comment]
Well after 2 weeks it died, some auth issue.  But I was running the old process in parallel with the same account, so it might have been related.

I restarted it again and stopped the parallel process, and let's see what happens.

**Comment by alc7328** [comment]
> and let's see what happens.

@NorthernMan54 please keep us updated!

**Comment by NorthernMan54** [comment]
Still not good

https://github.com/gphotosuploader/gphotos-uploader-cli/issues/331#issuecomment-1124265500
