### ISSUE TITLE
Error: spawn Unknown system error -8 

### ISSUE THREAD

**Issue by maisun** [Sunoo/homebridge-camera-ffmpeg#918]
Hi,
I can no longer get snapshots and videos from HomeKit via the plugin, I'm not sure when the issue started, but the setup worked fine for a few months up to now.
In the log I see lots of error:
Error: spawn Unknown system error -8 

And if I try to stream video it crashes Homebrige with the error:
[12/3/2020, 12:00:56 PM] Error: spawn Unknown system error -8
    at ChildProcess.spawn (internal/child_process.js:403:11)
    at Object.spawn (child_process.js:553:9)
    at new FfmpegProcess (/homebridge/node_modules/homebridge-camera-ffmpeg/src/ffmpeg.ts:15:20)
    at StreamingDelegate.startStream (/homebridge/node_modules/homebridge-camera-ffmpeg/src/streamingDelegate.ts:377:33)
    at StreamingDelegate.handleStreamRequest (/homebridge/node_modules/homebridge-camera-ffmpeg/src/streamingDelegate.ts:421:14)
    at RTPStreamManagement._handleStartStream (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:799:19)
    at RTPStreamManagement._handleSelectedStreamConfigurationWrite (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:630:14)
    at Characteristic.emit (events.js:315:20)
    at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:652:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1461:24
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1303:10)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:812:12)

Any suggestion where I should look? Thanks

**Comment by Sunoo** [comment]
Interesting... what OS are you running?

**Comment by maisun** [comment]
> Interesting... what OS are you running?

Hi Sunoo, thanks for replying! I run Homebridge as docker container on QNAP Linux based operating system. I have managed to solve the problem by creating a new docker container and install all plugins again. Luckily I could reuse the configuration so no re-config of my HomeKit devices. I don't have any clue what was the root cause.

**Comment by Sunoo** [comment]
Well, at least you got it working.

**Comment by ntqtuan** [comment]
Hi, I have a project laravel + vuejs in macos. I got this error, run the command 'npm run dev'.
 [webpack-cli] Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:415:11)
    at spawn (node:child_process:698:9)
    at Object.execFile (node:child_process:325:17)
    at Object.module.exports.fileCommandJson (/Users/panda/Sites/blog/node_modules/node-notifier/lib/utils.js:88:13)
    at NotificationCenter.notifyRaw (/Users/panda/Sites/blog/node_modules/node-notifier/notifiers/notificationcenter.js:81:11)
    at WebpackNotifierPlugin.compilationDone (/Users/panda/Sites/blog/node_modules/webpack-notifier/index.js:129:14)
    at _next1 (eval at create (/Users/panda/Sites/blog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:39:1)
    at eval (eval at create (/Users/panda/Sites/blog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:63:1) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}

please, help me

**Comment by Sunoo** [comment]
@ntqtuan None of this appears to have anything to do with this project?

**Comment by ntqtuan** [comment]
i got the above error can you help me

**Comment by Sunoo** [comment]
@ntqtuan Nothing in your stack track looks like anything to do with homebridge-camera-ffmpeg. If I’m wrong, please share your config and log. If I’m not, go talk to the project you’re actually using.
